### PR TITLE
Upgrade to ASP.NET Core 2.1

### PR DESCRIPTION
**Pull request by jrusbatch**
I made the least amount of changes possible to make this compatible with ASP.NET Core 2.1. If you decide to accept this, let me know if you want me to bump the version number.

### CODE REVIEW

**Comment by jotatoledo** [comment]
@billbogaiv would you mind reviewing this? Im currently unable to make use of your awesome package because of this incompatibility issue.

**Comment by billbogaiv** [comment]
Will take a look this afternoon. Not sure how I missed the notification when the PR was originally submitted. Thanks, @jrusbatch.

**Comment by billbogaiv** [comment]
@jrusbatch, @jotatoledo: Had to downgrade to `2.0.4`. See https://github.com/billbogaiv/hybrid-model-binding/pull/10.

😞 Ref. https://github.com/billbogaiv/hybrid-model-binding/issues/11
Ref. https://www.nuget.org/packages/HybridModelBinding/0.6.0

**Comment by billbogaiv** [comment]
Back up to 2.1 again 🎉: https://github.com/billbogaiv/hybrid-model-binding/issues/11

**Pull request merged**
